### ISSUE TITLE
http: proxy error: unsupported protocol scheme ""

### ISSUE THREAD

**Issue by ghosttie** [lox/httpcache#8] opened 2014-11-14 16:30 UTC
I have my proxy settings to only use httpcache for HTTP (not HTTPS) but I get this error when things like Dropbox try to use HTTPS:

    2014/11/14 11:26:11 http: proxy error: unsupported protocol scheme ""
    2014/11/14 11:26:11 127.0.0.1 "CONNECT //client-lb.dropbox.com:443 HTTP/1.1" (Internal Server Error) 0 ←[33;1mSKIP←[0m 0

I suspect it's because it's using // instead of specifying a scheme?  Is this something httpcache should be able to handle?

**Comment by lox** [comment] 2015-01-02 03:58
Interesting, what's seems to be happening is that your HTTP proxy is still being used for HTTPS requests, but over HTTP. What operating system are you using and how have you configured the proxies?

**Comment by ghosttie** [comment] 2015-01-02 04:22
Windows 8, I have it set to only use the proxy for HTTP and not for local addresses

**Comment by lox** [comment] 2015-08-09 22:43
Closing, as I can't reproduce.

**Closed by lox** 2015-08-09 22:43 UTC
